// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

interface ILeverV1PoolImmutables {
  /// @notice contract that deployed pool
  function factory() external view returns (address);

  /// @notice liquidity token generated by the pool
  function token() external view returns (address);

  /// @notice original nft collection that the pool supports
  function token0() external view returns (address);

  /// @notice synthetic nft collection generated by the pool
  function token1() external view returns (address);
}
